// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo7zboURhVtHBKqojeB888sb5SQnOZ-uE',
    appId: '1:379948840945:web:d86638681f025180907650',
    messagingSenderId: '379948840945',
    projectId: 'steppingstone-e8643',
    authDomain: 'steppingstone-e8643.firebaseapp.com',
    storageBucket: 'steppingstone-e8643.appspot.com',
    measurementId: 'G-Q7T0PVV7T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bIawFImZN-r4sWizwn3vWh047xuVHKY',
    appId: '1:379948840945:android:0b9da5b1f3c0a9f1907650',
    messagingSenderId: '379948840945',
    projectId: 'steppingstone-e8643',
    storageBucket: 'steppingstone-e8643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZEn6lS25bu5zXFHhuojQttFj2dEqCqg',
    appId: '1:379948840945:ios:81b7cfa9adbfcefa907650',
    messagingSenderId: '379948840945',
    projectId: 'steppingstone-e8643',
    storageBucket: 'steppingstone-e8643.appspot.com',
    iosClientId: '379948840945-3is4qb46hbrpjm7dlcl8t97fq5jd3j8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZEn6lS25bu5zXFHhuojQttFj2dEqCqg',
    appId: '1:379948840945:ios:20dbaef4990986d0907650',
    messagingSenderId: '379948840945',
    projectId: 'steppingstone-e8643',
    storageBucket: 'steppingstone-e8643.appspot.com',
    iosClientId: '379948840945-9ghfqhdrl1mh95nm3pljho3u332v89uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.steppingStoneApp',
  );
}
